name: auto
on: push  
jobs:
  display-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Required to access files
      - name: Display README.md
        run: ls
        
      - name: Display README.md
        run: echo "helloooooo"
        
      - name: Display README.md
        run: cat README.md
 
