name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'production'
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome Message
          run: echo "Hello"
        - name: List
          run: ls
        - name: Read
          run: cat README.md
