name: Cat README
on:
  workflow_dispatch:  # Allows manual trigger
jobs:
  display-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Required to access files
      - name: Set IMAGE_TAG from short commit SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Show IMAGE_TAG
        run: echo "The image tag is $IMAGE_TAG"

 
