name: First Job
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome Message
          run: echo "Hello"
        - name: List
          run: ls
        - name: Read
          run: cat README.md
